const PROVIDERS = {
  openrouter: {
    label: 'OpenRouter',
    envKey: 'OPENROUTER_API_KEY',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'nvidia/nemotron-3-nano-30b-a3b:free',
    models: [
      'nvidia/nemotron-3-nano-30b-a3b:free',
      'openai/gpt-oss-120b:free',
      'nvidia/nemotron-3-super-120b-a12b:free',
      'qwen/qwen3-coder:free',
      'openrouter/owl-alpha',
      'nex-agi/nex-n2-pro:free',
      'meta-llama/llama-3.3-70b-instruct:free',
      'google/gemma-4-31b-it:free',
    ],
  },
  openai: {
    label: 'OpenAI',
    envKey: 'OPENAI_API_KEY',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-5.4-mini',
    models: [
      'gpt-5.5',
      'gpt-5.4',
      'gpt-5.4-mini',
      'gpt-5.4-nano',
      'gpt-5.3-codex',
      'o3',
      'o3-mini',
      'gpt-4.1',
      'gpt-4o',
      'gpt-4o-mini',
    ],
  },
  anthropic: {
    label: 'Anthropic',
    envKey: 'ANTHROPIC_API_KEY',
    baseUrl: 'https://api.anthropic.com/v1',
    defaultModel: 'claude-sonnet-4-6',
    models: [
      'claude-opus-4-8',
      'claude-sonnet-4-6',
      'claude-haiku-4-5',
      'claude-opus-4-6',
      'claude-sonnet-4-5',
      'claude-3-5-sonnet',
    ],
  },
  google: {
    label: 'Google',
    envKey: 'GOOGLE_API_KEY',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    defaultModel: 'gemini-3.1-flash-lite',
    models: [
      'gemini-3.1-flash-lite',
      'gemini-3.5-flash',
      'gemini-3.1-pro',
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-2.5-flash-lite',
    ],
  },
  glm: {
    label: 'GLM',
    envKey: 'GLM_API_KEY',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    defaultModel: 'glm-4.7',
    models: [
      'glm-5.2',
      'glm-5.1',
      'glm-5',
      'glm-5-turbo',
      'glm-5-code',
      'glm-4.7',
      'glm-4.7-flash',
      'glm-4.5',
    ],
  },
  groq: {
    label: 'Groq',
    envKey: 'GROQ_API_KEY',
    baseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'llama-3.3-70b-versatile',
    models: [
      'llama-3.3-70b-versatile',
      'llama-4-scout',
      'qwen3-32b',
      'llama-3.1-8b-instant',
      'gpt-oss-120b',
      'gpt-oss-20b',
    ],
  },
  opencodezen: {
    label: 'OpenCode Zen',
    envKey: 'OPENCODE_API_KEY',
    baseUrl: 'https://opencode.ai/zen/v1',
    defaultModel: 'gpt-5.4-mini',
    models: [
      'gpt-5.5',
      'gpt-5.4',
      'gpt-5.4-mini',
      'gpt-5.4-nano',
      'gpt-5.3-codex',
      'gpt-5.2-codex',
      'claude-sonnet-4-6',
      'claude-haiku-4-5',
      'deepseek-v4-flash-free',
    ],
  },
  huggingface: {
    label: 'HuggingFace',
    envKey: 'HUGGINGFACE_API_KEY',
    baseUrl: 'https://router.huggingface.co/hf/v1',
    defaultModel: 'meta-llama/Llama-3.1-8B-Instruct',
    models: [
      'meta-llama/Llama-3.1-8B-Instruct',
      'Qwen/Qwen2.5-72B-Instruct',
      'meta-llama/Llama-3.2-11B-Vision-Instruct',
      'google/gemma-2-9b-it',
    ],
  },
  cloudflare: {
    label: 'Cloudflare',
    envKey: 'CLOUDFLARE_API_TOKEN',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1',
    defaultModel: '@cf/meta/llama-3.1-8b-instruct',
    models: [
      '@cf/meta/llama-3.1-8b-instruct',
      '@cf/meta/llama-3-8b-instruct',
      '@cf/meta/llama-3-70b-instruct',
      '@cf/qwen/qwen1.5-14b-chat',
      '@cf/mistral/mistral-7b-instruct-v0.2',
    ],
  },
  github: {
    label: 'GitHub',
    envKey: 'GITHUB_TOKEN',
    baseUrl: 'https://models.inference.ai.azure.com',
    defaultModel: 'gpt-4o-mini',
    models: [
      'gpt-4o-mini',
      'gpt-4o',
      'meta-llama-3.1-405b-instruct',
      'meta-llama-3.1-70b-instruct',
      'meta-llama-3.1-8b-instruct',
      'cohere-command-r-plus',
      'mistral-large-2',
    ],
  },
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROVIDERS };
}
